image:
  registry: docker.io
  repository: mongo
  tag: 4.4.10
  pullPolicy: IfNotPresent
auth:
  enabled: false
architecture: standalone
useStatefulSet: true
replicaCount: 1
service:
  type: ClusterIP
  ports:
    mongodb: 27017
persistence:
  enabled: true
  mountPath: /data/db
  size: 20Gi
command:
  - mongod
  - --replSet
  - debezium
  - --bind_ip_all
extraEnvVars:
  - name: MONGO_INITDB_DATABASE
    value: "python_backend"
  - name: MONGO_INITDB_FEATURES
    value: "1"